[Metadata]
Name=Mac Rime Light
Name[zh_CN]=Mac Rime 浅色
Version=1
Author=Borber
Description=Rounded macOS-like light theme for Fcitx5 Rime
ScaleWithDPI=True

[InputPanel]
NormalColor=#3f3f3f
HighlightCandidateColor=#ffffff
HighlightColor=#ffffff
HighlightBackgroundColor=#08b978
LabelTextSizeFactor=72
CandidateLabelColor=#777777
HighlightCandidateLabelColor=#d9fff0
PageButtonAlignment=Last Candidate

[InputPanel/TextMargin]
Left=3
Right=3
Top=4
Bottom=4

[InputPanel/ContentMargin]
Left=11
Right=11
Top=6
Bottom=12

[InputPanel/Background]
Image=panel.png

[InputPanel/Background/Margin]
Left=18
Right=18
Top=20
Bottom=22

[InputPanel/Highlight]
Image=highlight.png

[InputPanel/Highlight/Margin]
Left=6
Right=6
Top=4
Bottom=3

[InputPanel/PrevPage]
Image=prev.png

[InputPanel/PrevPage/ClickMargin]
Left=6
Right=6
Top=4
Bottom=4

[InputPanel/NextPage]
Image=next.png

[InputPanel/NextPage/ClickMargin]
Left=6
Right=6
Top=4
Bottom=4

[Menu]
NormalColor=#3f3f3f
HighlightCandidateColor=#ffffff

[Menu/Background]
Image=panel.png

[Menu/Background/Margin]
Left=18
Right=18
Top=20
Bottom=22

[Menu/ContentMargin]
Left=11
Right=11
Top=6
Bottom=12

[Menu/CheckBox]
Image=radio.png

[Menu/SubMenu]
Image=arrow.png

[Menu/Highlight]
Image=highlight.png

[Menu/Highlight/Margin]
Left=6
Right=6
Top=4
Bottom=3

[Menu/Separator]
Color=#999999

[Menu/TextMargin]
Left=6
Right=6
Top=4
Bottom=4

[AccentColorField]
0=Input Panel Border
1=Input Panel Highlight Candidate Background
2=Input Panel Highlight
3=Menu Border
4=Menu Separator
5=Menu Selected Item Background
