-- Auto-generated by DMS - do not edit directly.
-- Require this module from hyprland.lua to enable these colors.

local primary = "rgb(907aa9)"
local outline = "rgb(797593)"
local error = "rgb(b4637a)"

hl.config({
  general = {
    col = {
      active_border = primary,
      inactive_border = outline,
    },
  },

  group = {
    col = {
      border_active = primary,
      border_inactive = outline,
      border_locked_active = error,
      border_locked_inactive = outline,
    },

    groupbar = {
      col = {
        active = primary,
        inactive = outline,
        locked_active = error,
        locked_inactive = outline,
      },
    },
  },
})
