-- Auto-generated by DMS - do not edit manually
-- Require this module from hyprland.lua to enable this layout.

hl.config({
  general = {
    gaps_in = 4,
    gaps_out = 4,
    border_size = 2,
  },

  decoration = {
    rounding = 12,
  },
})
